### PR TITLE
Convert Java Project to Maven Project

### PR DESCRIPTION
**Pull request by derickfelix**
I've created a maven module with 10 sub-modules, the main (escpos-coffee) and the samples inside 
'samples/' folder.

You can build the entire project ./mvnw clean package

*NO CODE WERE CHANGED*
The samples were tested and worked successfully.

Feel free to test or change anything you like.

### CODE REVIEW

**Comment by anastaciocintra** [comment]
Good @derickfelix,
I will check on the weekend

**Comment by anastaciocintra** [comment]
Hi @derickfelix 
this project is growing and we need to take some precautions ...
I feel responsible for writing some procedures for the contributors and I apologize for not having determined them yet ...

(this is one draft of procedures)

- open issue
- create project if necessary
- create a xyz branch
- code in xyz branch
- test in the xyz branch
- pull request to master
- release version


Going back to the topic, transforming the build process into maven is not simple, as we need to respect everyone who downloads and is working with this library.
I also thought about putting it in the public repository and I will need to participate in this, I am already reading some materials to see how to do this.
If you consent, can we do this way "more professional"?

[], Marco

**Comment by anastaciocintra** [comment]
Dear @derickfelix,
please, put these changes on another branch other then master, for example, 'maven development' branch

**Comment by derickfelix** [comment]
Ok, I agree, I have made it quickly, cuz I had to use it soon.

**Pull request merged**
