### PR TITLE
Update EscPos.java

### PR DESCRIPTION
**Pull request by Muraveiko**
bug. LF char need

https://github.com/anastaciocintra/escpos-coffee/issues/17

### CODE REVIEW

**Comment by anastaciocintra** [comment]
@Muraveiko ,
very good!
  this patch has been incorporated into fix-writeLF
and generated 2.0.2-SNAPSHOT on repository.
A few more tests and we can launch the RELEASE.

**Comment by anastaciocintra** [comment]
@Muraveiko,
Just for testing purposes, I need some information about how to reproduce the problem, any tip?

**Comment by Muraveiko** [comment]
https://photos.app.goo.gl/6YCMZN4zezVLNVPK9
before with you example and after my 
https://github.com/402d/RawBt-and-ESCPOS-coffee/blob/master/app/src/main/java/ru/a402d/escpos_coffee/MainActivity.java#L129

china printers: zjing & goojprt . 

see also
https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/Printer.php#L523
https://github.com/mike42/escpos-php/blob/development/example/receipt-with-logo.php#L34
chr10 as part of string ;)

**Comment by anastaciocintra** [comment]
https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/Printer.php#L523

**this was adjusted too**

**Pull request merged**
